// <auto-generated />
namespace Keno.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Addattendanceandupdatesalecode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addattendanceandupdatesalecode));
        
        string IMigrationMetadata.Id
        {
            get { return "201911101135114_Add attendance and update sale code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
