// <auto-generated />
namespace Keno.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddstatisticsandUploader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddstatisticsandUploader));
        
        string IMigrationMetadata.Id
        {
            get { return "201911031653045_Add statistics and Uploader"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
