// <auto-generated />
namespace Keno.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addattendancelist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addattendancelist));
        
        string IMigrationMetadata.Id
        {
            get { return "201911101133422_Add attendance list"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
