// <auto-generated />
namespace Keno.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updatemodel11102019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updatemodel11102019));
        
        string IMigrationMetadata.Id
        {
            get { return "201911101328316_Update model 11102019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
